# YAML-Language Server: $schema=https://raw.githubusercontent.com/dotnet/docfx/main/schemas/filterconfig.schema.json
apiRules:
  - exclude:
      uidRegex: ^Uno\.Resizetizer$
      type: namespace
  - exclude:
      uidRegex: ^DevTKSS\.Uno\.Samples\.MvuxGallery\.ReactiveViewModelMappings$
      type: namespace
  - exclude:
      uidRegex: ^__Reactive$
      type: method